---
driver:
  name: vagrant

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 1
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  requirements_path: requirements.yml
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  idempotency_test: true
  additional_copy_path:
    - extra_modules
    - filter_plugins
    - extra_roles
  ansible_vault_password_file: <%= File.expand_path(ENV['ANSIBLE_VAULT_PASSWORD_FILE'] || '') %>

platforms:
# XXX the package for ubuntu 14.04 is broken
#  - name: ubuntu-14.04-amd64
#    driver:
#      box: trombik/ansible-ubuntu-14.04-amd64
#      box_check_update: false

  - name: ubuntu-16.04-amd64
    driver:
      box: trombik/ansible-ubuntu-16.04-amd64
      box_check_update: false

  - name: debian-8,7-amd64
    driver:
      box: trombik/ansible-debian-8.7-amd64
      box_check_update: false

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I tests/serverspec tests/serverspec/default_spec.rb
